name: 'Deploy Test'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  get_tf_folders:
    name: 'Get Terraform folders'
    runs-on: azure-cicd

    defaults:
      run:
        shell: bash

    outputs:
      directories: ${{ steps.transform.outputs.directories }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get all changed files  
      id: files
      uses: tj-actions/changed-files@v41
      with:
        files: |
            **.tf
        dir_names: true

    - name: Transform to terraform directories
      id: transform
      continue-on-error: false
      run: |
        folders=()
        for dir in ${{ steps.files.outputs.dirs }}; do
              echo "Adding ${dir} to folders"
              folders+=${dir}
        done
        unique_folders=($(printf "%s\n" "${folders[@]}" | sort -u | tr '\n' ' '))
        folders_json="["
        for f in ${unique_folders[@]}; do
            folders_json+="\"$f\","
        done
        folders_json="${folders_json%,}]"
        echo "directories=${folders_json}"
        echo "directories=${folders_json}" >> $GITHUB_OUTPUT