on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  serialize:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.build.outputs.directories }}
    steps:
      - name: Build in ${{ inputs.folder}}
        id: build
        run: |
          first_folder="${{ inputs.folder }}_1"
          second_folder="${{ inputs.folder }}_2"
          json_folders="[\"${first_folder}\",\"${second_folder}\"]"
          echo "directories=${json_folders}"
          echo "directories=${json_folders}" >> $GITHUB_OUTPUT

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test in ${{ inputs.folder }}
  #       run: |
  #         echo "Test in ${{ inputs.folder }}"

  deploy:
    needs: [serialize]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tf_folder: ${{ fromJSON(needs.serialize.outputs.directories) }}

    steps:
      - name: Init in ${{ matrix.tf_folder }}
        run: |
          echo "Deploy in ${{ matrix.tf_folder }}"

      - name: Validate in ${{ matrix.tf_folder }}
        run: |
          echo "Validate in ${{ matrix.tf_folder }}"