name: 'Azure Terraform'

on: [push, pull_request]

jobs:
  get_changed_files:
    name: 'Get changed files'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    outputs:
      pushed_chg_files: ${{ steps.store.outputs.pushed_chg_files }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Install python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10' 

    - name: Get all changed files  
      id: files
      uses: masesgroup/retrieve-changed-files@v3

    - name: Store all changed files
      id: store
      run: |
        echo "pushed_chg_files=${{ steps.files.outputs.added_modified }}" >> "$GITHUB_OUTPUT"

    # - name: Do something with changed files
    #   run: |
    #     for changed_file in ${{ steps.files.outputs.added_modified }}; do
    #       echo "Do something with this ${changed_file}."
    #     done

  terraform:
    name: 'Run Terraform'
    needs: get_changed_files
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Retrieve pushed changed files
      run: |
        for changed_file in ${{ needs.get_changed_files.outputs.pushed_chg_files }}; do
          echo "Do something with this ${changed_file}."
        done