name: 'Get changed files'

on: [push, pull_request]

jobs:
  terraform:
    name: 'Get changed files'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    -name: List changed files  
      id: files
      uses: masesgroup/retrieve-changed-files@v3
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done