name: 'Azure Terraform Self-hosted'

on: [push, pull_request]

jobs:
  get_tf_folders:
    name: 'Get Terraform folders'
    runs-on: azure-cicd

    defaults:
      run:
        shell: bash

    outputs:
      directories: ${{ steps.transform.outputs.directories }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get all changed files  
      id: files
      uses: masesgroup/retrieve-changed-files@v3

    - name: List files
      run: |
        ls -lrt