name: 'Azure Terraform'

on: [push, pull_request]

jobs:
  get_tf_folders:
    name: 'Get Terraform folders'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    outputs:
      directories: ${{ steps.transform.outputs.directories }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get all changed files  
      id: files
      uses: masesgroup/retrieve-changed-files@v3

    - name: Transform to directories
      id: transform
      continue-on-error: false
      run: |
        folders=()
        for f in ${{ steps.files.outputs.added_modified }}; \
          do \
            echo "${f}" | grep -qi ".*tf"
            echo "Adding $(dirname $f) to folders"; \
            folders+=($(dirname $f)); \
        done
        unique_folders=($(printf "%s\n" "${folders[@]}" | sort -u | tr '\n' ' '))
        echo "directories=$(jq --compact-output --null-input '$ARGS.positional' --args -- ${unique_folders[@]})"
        echo "directories=$(jq --compact-output --null-input '$ARGS.positional' --args -- ${unique_folders[@]})" >> $GITHUB_OUTPUT

  terraform:
    name: 'Run Terraform Par'
    needs: get_tf_folders
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        # tf_folder: ${{ needs.get_changed_files.outputs.pushed_chg_files }}
        tf_folder: ${{ fromJSON(needs.get_tf_folders.outputs.directories) }}
 
    steps:

    - name: Terraform Init
      run: |
        echo "Do terraform init with ${{ matrix.tf_folder }}"

    - name: Terraform Validate
      run: |
        echo "Do terraform validate with ${{ matrix.tf_folder }}"