name: 'Manage Infra By Dispatch'

on:
  workflow_dispatch:
    inputs:
      # Working directory input from user.
      directory:
        description: Choose root directory to run TF apply/destroy
        default: "infra/kstp"
        required: true
        type: string
      # Terraform action to execute plan/apply/destroy
      action:
        description: Choose Terraform Action
        default: "plan"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

defaults:
  run:
    shell: bash

jobs:
  # Order TF folders to follow specific dependencies
  order_tf_folders:
    name: 'Order TF Folders'
    runs-on: ${{ vars.RUNNER }}
    outputs:
      ordered_tf_folders: ${{ steps.tfdirs_order.outputs.ordered_dirs }}

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Perform Ordering (using python script) of TF folders based on the specified action
    - name: Perform Ordering
      id: tfdirs_order
      run: |
        ordered_dirs=$(python .github/scripts/tf_order_by_action.py "${{ github.event.inputs.action }}" "${{ github.event.inputs.directory }}")
        echo "ordered_dirs=${ordered_dirs}"
        echo "ordered_dirs=${ordered_dirs}" >> $GITHUB_OUTPUT

  # Execute reusable workflow for every group of TF folders and action specified
  terraform_flow:
    name: 'Execute Terraform'
    needs: [order_tf_folders]
    strategy:
      matrix:
        folders_string_list: ${{ fromJSON(needs.order_tf_folders.outputs.ordered_tf_folders) }}
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/terraform-action.yml
    with:
      folders_string: ${{ matrix.folders_string_list }}
      tf_action: ${{ github.event.inputs.action }}
    secrets: inherit