name: 'Terraform Flow'

on:
  workflow_call:
    inputs:
      folders_string:
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  TF_LOG: INFO

jobs:
  prepare_matrix:
    name: 'Prepare Matrix'
    runs-on: ${{ vars.RUNNER }}
    outputs:
      dirs: ${{ steps.set_matrix.outputs.dirs }}
    steps:
      # Set matrix of jobs to run Terraform in parallel for every folder in matrix
      - name: Set matrix for ${{ inputs.folders_string }}
        id: set_matrix
        run: |
          matrix_arr=(${{ inputs.folders_string }})
          matrix_arr_json="["
          for dir in ${matrix_arr[@]}; do
            matrix_arr_json+="\"${dir}\","
          done
          matrix_arr_json="${matrix_arr_json%,}]"
          echo "dirs=${matrix_arr_json}"
          echo "dirs=${matrix_arr_json}" >> $GITHUB_OUTPUT

  deploy:
    name: 'Run Terraform'
    needs: [prepare_matrix]
    runs-on: ${{ vars.RUNNER }}

    strategy:
      matrix:
        tf_folder: ${{ fromJSON(needs.prepare_matrix.outputs.dirs) }}

    steps:
      # Checkout the repository if it's running on github runner 'ubuntu-latest', skip for self-hosted one
      - name: Checkout
        if: ${{ vars.RUNNER == 'ubuntu-latest' }}
        uses: actions/checkout@v2
        
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        working-directory: ${{ matrix.tf_folder }}
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        run: |
          CONTAINER_ENV=$(echo "${{ matrix.tf_folder }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          CONTAINER_NAME="${CONTAINER_ENV}-kstp-tf-state-blob"
          LOCK_KEY_PATH=$(echo "${{ matrix.tf_folder }}" | cut -d'/' -f3-)
          LOCK_KEY_TFSTATE="${LOCK_KEY_PATH}/terraform.tfstate"
          terraform init -upgrade -lock=false -reconfigure \
            -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="resource_group_name=$RESOURCE_GROUP" \
            -backend-config="key=${LOCK_KEY_TFSTATE}"

      # Run a terraform validate to check the syntax and configuration based on the core syntax of Terraform code
      - name: Terraform Validate
        working-directory: ${{ matrix.tf_folder }}
        id: validate
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform validate -no-color
          echo "result=$(terraform validate -no-color)" >> $GITHUB_OUTPUT

      # Run a terraform plan for pull requests only
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ${{ matrix.tf_folder }}
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform plan -no-color
          echo 'result<<EOF' >> $GITHUB_OUTPUT
          terraform plan -no-color >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      # Add a comment to pull requests with plan results
      - name: Add Plan Comment
        if: github.event_name == 'pull_request'
        id: comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.result }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`
            ${{ steps.plan.outputs.result }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ matrix.tf_folder }}\`, Workflow: \`${{ github.workflow }}\`*
            `;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        working-directory: ${{ matrix.tf_folder }}
        id: apply
        # if github.ref == 'refs/heads/master' && github.event_name == 'push'
        if: github.event.review.state == 'APPROVED'
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve

      # Add a comment to pull requests with plan results
      - name: Add Apply Comment
        if: github.event.review.state == 'APPROVED'
        id: apply_comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Terraform Apply 📖\`${{ steps.apply.outcome }}\`

            <details><summary>Show Apply</summary>

            \`\`\`
            ${{ steps.apply.outputs.result }}
            \`\`\`

            </details>

            *Applier: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ matrix.tf_folder }}\`, Workflow: \`${{ github.workflow }}\`*
            `;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })