on:
  workflow_call:
    inputs:
      folders_string:
        required: true
        type: string

jobs:
  prepare_matrix:
    name: 'Prepare Matrix'
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.set_matrix.outputs.directories }}
    steps:
      - name: Set matrix for ${{ inputs.folders_string }}
        id: set_matrix
        run: |
          matrix_arr=(${{ inputs.folders_string }})
          matrix_arr_json="["
          for dir in ${matrix_arr[@]}; do
            matrix_arr_json+="\"${dir}\","
          done
          matrix_arr_json="${matrix_arr_json%,}]"
          echo "directories=${matrix_arr_json}"
          echo "directories=${matrix_arr_json}" >> $GITHUB_OUTPUT

  deploy:
    name: 'Run Terraform'
    needs: [prepare_matrix]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tf_folder: ${{ fromJSON(needs.prepare_matrix.outputs.directories) }}

    steps:
      - name: Init in ${{ matrix.tf_folder }}
        run: |
          echo "Deploy in ${{ matrix.tf_folder }}"

      - name: Validate in ${{ matrix.tf_folder }}
        run: |
          echo "Validate in ${{ matrix.tf_folder }}"